name: atom_attendance
description: "Attendance management app for Atom employees."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.0
  intl: ^0.19.0
  # Excel version ko fix kiya taake archive package ka conflict na ho
  excel: 4.0.6 
  path_provider: ^2.1.0
  share_plus: ^10.0.0
  cupertino_icons: ^1.0.8
  geolocator: ^14.0.2
  dart_ipify: ^1.1.1
  geolocator_web: ^4.1.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Version update kiya compatibility ke liye
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

# YEH SECTION SABSE IMPORTANT HAI CONFLICT KHATAM KARNE K LIYE
dependency_overrides:
  archive: ^3.6.1

flutter:
  uses-material-design: true
  assets:
    - shorebird.yaml
    - assets/icon.png
    - assets/support/jazzcash.png
    - assets/support/binance.png
    - assets/support/crpto_address.jfif

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#0D1117"
  adaptive_icon_foreground: "assets/icon.png"

flutter_native_splash:
  color: "#0D1117"
  image: assets/icon.png
  android_12:
    image: assets/icon.png
    color: "#0D1117"
  fullscreen: true